In [1]:
fileName ="PathaoFoodDeliveryData"

In [2]:
import pandas

In [3]:
data= pandas.read_csv(fileName)

In [12]:
data_sorted = data.sort_values(['restaurant_id'], ascending=False)

In [13]:
data_sorted

user_id       item_id  dow  hod   category_id  \
181909  5867166128242373928  6bace9cb-f78    6   23  fab86226-722   
292131   430533841450840734  ac8646f6-60d    5   22  d0bb456a-a3e   
145992  5867166128242373928  46c78d57-f2f    6   23  1973d90d-e95   
8170   -3277971590148499419  f9069482-824    3    0  b71f83a7-20c   
135617  4107206122072798772  c9a250ec-3de    4    2  a7686e22-07a   
150470  5081630822441645599  5af92099-c64    2   23  a7686e22-07a   
280777 -9061309185205270407  162b26b1-820    7    0  c4a71e77-3ac   
289893   430533841450840734  2b7cc6a6-6a5    7   18  21c696d5-bfd   
147023   917086523880260900  c9a250ec-3de    4    1  a7686e22-07a   
264362 -5231415824383510038  1d91b451-5e7    5   21  2198aa1f-cbb   
159077 -9061309185205270407  c8f31ab1-2c3    7    0  9511cb6d-e49   
172352  2323469022922044523  410d866a-2d1    1   17  171d8fef-da7   
172739  1088485998810495156  c8ba20f9-1d6    2    1  c0bbf117-c18   
171160 -4905929543610527615  c54e6e0a-04e    4   20  171d8fef-da7   
175306   827174265091700507  a8530115-12d    2   23  c0bbf117-c18   
170407 -7335621514653369885  1db07832-c2e    7    2  c0bbf117-c18   
172325 -8847977655050695629  892b50f3-15e    3    2  171d8fef-da7   
171304  3349925720890339310  ed277500-10b    5   20  171d8fef-da7   
299894 -7701484607770708446  304243c5-3b1    6   23  7da02ec9-6d6   
177479 -3904187539607190330  0561dc0f-bf4    1    0  171d8fef-da7   
175493  1088485998810495156  71e98b7a-838    2    1  c0bbf117-c18   
187548  1088485998810495156  db42a68e-864    2    1  f054e6bc-144   
172276  2239729271861083091  f55e6a79-ebd    1    5  c0bbf117-c18   
210014 -7639209610514629956  3461ee24-a86    1    5  bee653fb-187   
209729  2239729271861083091  3461ee24-a86    7    5  bee653fb-187   
194153  7616933445097100632  6a8191eb-fb1    2    5  f054e6bc-144   
173936  1088485998810495156  f55e6a79-ebd    2    1  c0bbf117-c18   
174141 -7335621514653369885  a8cebafe-824    7    2  c0bbf117-c18   
175371 -5928115624228688031  ed277500-10b    3   18  171d8fef-da7   
179235  1088485998810495156  1db07832-c2e    2    1  c0bbf117-c18   
...                     ...           ...  ...  ...           ...   
74248  -5423096324561235136  4b5d5f87-9f1    3   20  32f04135-0ea   
187352 -4584083936632074672  0630c00e-686    7   23  81beda5f-34b   
71488  -6872960916617605148  a238eeb7-475    5    3  32f04135-0ea   
206438 -1706099096955500687  db953a78-e47    5   22  81beda5f-34b   
76021  -3758175471431111870  a238eeb7-475    6    3  32f04135-0ea   
182998 -1706099096955500687  0630c00e-686    5   22  81beda5f-34b   
187228 -1034926418817825621  0630c00e-686    7   21  81beda5f-34b   
194724  2026028468529350089  3a370b3c-2a8    3   19  81beda5f-34b   
201457  1176106403410717865  3a370b3c-2a8    5   21  81beda5f-34b   
207783 -1706099096955500687  e03c0058-f06    5   22  81beda5f-34b   
69466  -3758175471431111870  b51fdd15-531    6    3  32f04135-0ea   
197769 -5423096324561235136  3a370b3c-2a8    3   20  81beda5f-34b   
205757  6382516717860657683  0630c00e-686    4    0  81beda5f-34b   
77555  -6257291270711658900  a238eeb7-475    7    2  32f04135-0ea   
208503 -1792298815260335370  e03c0058-f06    1    2  81beda5f-34b   
76339  -4975885649327977242  fa490229-1aa    2    0  32f04135-0ea   
199972 -4584083936632074672  0630c00e-686    1    1  81beda5f-34b   
74600  -4975885649327977242  4b5d5f87-9f1    2    0  32f04135-0ea   
199490  6382516717860657683  e03c0058-f06    4    0  81beda5f-34b   
195250  -771899697155891775  3a370b3c-2a8    4   22  81beda5f-34b   
253356 -6872960916617605148  9de0935e-8e4    5    3  791ed575-011   
253642 -2176674044130060964  9de0935e-8e4    6    2  791ed575-011   
202284 -2176674044130060964  3a370b3c-2a8    6    2  81beda5f-34b   
185171  -771899697155891775  0630c00e-686    4   22  81beda5f-34b   
79273  -1034926418817825621  fa490229-1aa    7   21  32f04135-0ea   
189812  6382516717860657683  3a370b3c-2a8    4    0  81beda5f-34b   
196547 -4975885649

In [6]:
setUid = set(data["user_id"])
setItemID = set(data["item_id"])
setRestaurantID = set(data["restaurant_id"])

In [105]:
uids = list(setUid)
itemID = list(setItemID)
restaurantID = list(setRestaurantID)

In [157]:
itemDayHour = data.values[:, [1, 2, 3]]

In [158]:
itemID_len = len(itemID)
for i in range(itemID_len):
    _index = np.where(itemDayHour[:, 0] == itemID[i])
    #print(itemDayHour[_index])
    itemDayHour[_index, 0] = i
    #print(itemDayHour[_index])

In [161]:
itemID_len = len(itemID)
for i in range(itemID_len):
    data['item_id'].replace(
        to_replace=[itemID[i]],
        value=i,
        inplace=True
    )

In [162]:
#itemDayHour
data

user_id  item_id  dow  hod   category_id     cusine_id  \
0      -6088859261566846925     1822    7    3  9c64431e-79f  fb8b5b7f-013   
1      -4662982070704311223    49872    7    2  a989cb37-db5  8631ea96-a78   
2      -4849981472186386714    44768    1    1  4f31b9ea-059  5aa1a680-942   
3      -5400975689533971605     1744    4    0  37d510f8-745  c9aa3993-86f   
4       4810905585891548302     6250    3    1  4264559d-470  5aa1a680-942   
5       8523163246689801258    36285    2    3  60db56cd-21e  2d470ebd-e46   
6       6141444640923780397    52225    6   17  b7226a64-569  5aa1a680-942   
7       7782246672655206426    32742    2   23  68f8231d-6e1  8631ea96-a78   
8      -3808793554476278979    49829    5    5  79803e34-c64  e153fa17-ac6   
9       2565395798581291385    52791    2    4  21b8380d-5d8  e153fa17-ac6   
10     -3489746803649220895     8683    7    5  bea84e89-386  1e1b7be1-255   
11     -1688322991209493915    29328    5    4  b151a742-1a8  a05f43a8-869   
12     -8833694771524589944    23681    1    0  867c1a08-40e  5aa1a680-942   
13     -3077683177680922383    42363    6    2  b99c7447-fe5  c9aa3993-86f   
14      3981900218727713260    25588    3   22  fd95cf04-e42  5aa1a680-942   
15      5680980253065770929    45147    1    3  b2cb3087-065  5aa1a680-942   
16     -3453900085104082485       95    5    2  270a3755-aa0  0839d354-1b6   
17      5898322097636037327    13650    5    0  fd2833ea-fb8  1e1b7be1-255   
18      1257294476142262241    10818    6    1  9f0c801f-a91  5aa1a680-942   
19      2455213091235929902     3776    7    1  4eb5f516-733  a05f43a8-869   
20      8848300206222508169    45697    4   18  4ab0668f-3c0  3f55fbbf-673   
21      1504209790039813286    20716    2   19  b47b70e3-80a  0839d354-1b6   
22     -3393345818928047780    50279    6   17  3a8e2c92-467  8631ea96-a78   
23      2606689623785405541    15014    6    6  94d5bcb7-955  ba1a45f9-274   
24      -858644981621013365     4117    3   21  b47b70e3-80a  0839d354-1b6   
25      4521991327218557979     6739    4    1  570ddd69-916  5aa1a680-942   
26      -204203713088148524     8683    3    6  bea84e89-386  1e1b7be1-255   
27      2203884751206800993    51624    3   22  f6684ecb-2e0  c9aa3993-86f   
28      7793727790636132789    46054    6    3  6275d91b-a57  8631ea96-a78   
29     -1050723095260732421    13271    3    3  b92f4add-a85  5aa1a680-942   
...                     ...      ...  ...  ...           ...           ...   
323108  5350435017533364742    45014    3    3  b451c65d-5a9  fe93edb5-39e   
323109 -8808703556370141141    31152    6    2  7f93d955-792  fe93edb5-39e   
323110  3411136294828814308     4056    2    3  28aa49b5-8d4  fe93edb5-39e   
323111  9032854072109279443     4271    2    4  c354e9b6-c64  fe93edb5-39e   
323112  3929221392677988083    29414    3   17  2d15d4bc-5dc  fe93edb5-39e   
323113   798225392702878042    39560    6   16  2e8cdf4c-420  fe93edb5-39e   
323114  3061227359551306603    32183    3   22  8c3bc18b-9f8  fe93edb5-39e   
323115  2619002138196071920    49606    5    0  1e07059d-9f7  fe93edb5-39e   
323116  7632060087693694058    17708    6    0  ced04d74-bd4  fe93edb5-39e   
323117  8274422197676497095    22215    7    3  00006e9c-b5c  fe93edb5-39e   
323118 -7628982420231152669    26947    7    1  e5cab48b-20b  fe93edb5-39e   
323119  4805771485126816513    33570    1   19  ced04d74-bd4  fe93edb5-39e   
323120  2831889166812781786    44144    6   22  96d29ec3-27b  fe93edb5-39e   
323121 -5784251526134776958    23513    4    3  2e283b5c-cc7  fe93edb5-39e   
323122 -9005765622695841613     8140    5   21  e1d9a51e-04f  fe93edb5-39e   
323123  -605029847216078503    45913    6    4  153341b8-056  fe93edb5-39e   
323124 -4442622314382671752      747    3    3  37c06ba2-d19  fe93edb5-39e   
323125  8859529524441020285    22645    3   16  b78deced-1ff  fe93edb5-39e   
323126  7316919665761703176    45184    1    2  7a475177-60e  fe93edb5-39e   
323127 -2870640926558097794    49691    4 

In [164]:
#pandas.DataFrame(itemDayHour).to_csv("data_2_.csv")
pandas.DataFrame(data.values).to_csv("data_2_.csv")

In [165]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

In [172]:
X = itemDayHour[:,[1,2]].astype(np.int)

In [173]:
X

array([[ 7,  3],
       [ 7,  2],
       [ 1,  1],
       ..., 
       [ 7, 15],
       [ 6,  5],
       [ 4,  4]])

In [174]:
Y = itemDayHour[:,0].astype(np.int)

In [175]:
Y

array([ 1822, 49872, 44768, ..., 15164, 50719, 14412])

In [176]:
clf.fit(X, Y)

GaussianNB(priors=None)

In [183]:
print(clf.predict_proba([[ 7,  3]]))

[[  0.00000000e+00   0.00000000e+00   2.52515476e-12 ...,   0.00000000e+00
    0.00000000e+00   3.58738222e-11]]


In [179]:
clf.classes_

array([    0,     1,     2, ..., 53400, 53401, 53402])