In [73]:
fileName ="data_2_.csv"

In [74]:
import pandas
import numpy as np

In [75]:
data= pandas.read_csv(fileName)

In [76]:
data_sorted = data.sort_values(['restaurant_id'], ascending=False)

In [77]:
data_sorted

Unnamed: 0              user_id  item_id  dow  hod   category_id  \
181909      181909  5867166128242373928    17525    6   23  fab86226-722   
292131      292131   430533841450840734    48244    5   22  d0bb456a-a3e   
145992      145992  5867166128242373928    48752    6   23  1973d90d-e95   
8170          8170 -3277971590148499419    26101    3    0  b71f83a7-20c   
135617      135617  4107206122072798772    43806    4    2  a7686e22-07a   
150470      150470  5081630822441645599    46472    2   23  a7686e22-07a   
280777      280777 -9061309185205270407    47107    7    0  c4a71e77-3ac   
289893      289893   430533841450840734      395    7   18  21c696d5-bfd   
147023      147023   917086523880260900    43806    4    1  a7686e22-07a   
264362      264362 -5231415824383510038     5448    5   21  2198aa1f-cbb   
159077      159077 -9061309185205270407    26777    7    0  9511cb6d-e49   
172352      172352  2323469022922044523    53223    1   17  171d8fef-da7   
172739      172739  1088485998810495156    32336    2    1  c0bbf117-c18   
171160      171160 -4905929543610527615     5959    4   20  171d8fef-da7   
175306      175306   827174265091700507    21292    2   23  c0bbf117-c18   
170407      170407 -7335621514653369885    53327    7    2  c0bbf117-c18   
172325      172325 -8847977655050695629    33067    3    2  171d8fef-da7   
171304      171304  3349925720890339310    30771    5   20  171d8fef-da7   
299894      299894 -7701484607770708446    22485    6   23  7da02ec9-6d6   
177479      177479 -3904187539607190330    45927    1    0  171d8fef-da7   
175493      175493  1088485998810495156      287    2    1  c0bbf117-c18   
187548      187548  1088485998810495156     4756    2    1  f054e6bc-144   
172276      172276  2239729271861083091    28733    1    5  c0bbf117-c18   
210014      210014 -7639209610514629956    29657    1    5  bee653fb-187   
209729      209729  2239729271861083091    29657    7    5  bee653fb-187   
194153      194153  7616933445097100632    28855    2    5  f054e6bc-144   
173936      173936  1088485998810495156    28733    2    1  c0bbf117-c18   
174141      174141 -7335621514653369885    38725    7    2  c0bbf117-c18   
175371      175371 -5928115624228688031    30771    3   18  171d8fef-da7   
179235      179235  1088485998810495156    53327    2    1  c0bbf117-c18   
...            ...                  ...      ...  ...  ...           ...   
74248        74248 -5423096324561235136     5017    3   20  32f04135-0ea   
187352      187352 -4584083936632074672    50334    7   23  81beda5f-34b   
71488        71488 -6872960916617605148    30934    5    3  32f04135-0ea   
206438      206438 -1706099096955500687    50869    5   22  81beda5f-34b   
76021        76021 -3758175471431111870    30934    6    3  32f04135-0ea   
182998      182998 -1706099096955500687    50334    5   22  81beda5f-34b   
187228      187228 -1034926418817825621    50334    7   21  81beda5f-34b   
194724      194724  2026028468529350089    41770    3   19  81beda5f-34b   
201457      201457  1176106403410717865    41770    5   21  81beda5f-34b   
207783      207783 -1706099096955500687    16982    5   22  81beda5f-34b   
69466        69466 -3758175471431111870     6190    6    3  32f04135-0ea   
197769      197769 -5423096324561235136    41770    3   20  81beda5f-34b   
205757      205757  6382516717860657683    50334    4    0  81beda5f-34b   
77555        77555 -6257291270711658900    30934    7    2  32f04135-0ea   
208503      208503 -1792298815260335370    16982    1    2  81beda5f-34b   
76339        76339 -4975885649327977242    10346    2    0  32f04135-0ea   
199972      199972 -4584083936632074672    50334    1    1  81beda5f-34b   
74600        74600 -4975885649327977242     5017    2    0  32f04135-0ea   
199490      199490  6382516717860657683    16982    4    0  81beda5f-34b   
195250      195250  -771899697155891775    41770    4   22  81beda5f-34b   
253356      253356 -6872960916617605148      824    5   

In [84]:
data_sorted_array = data_sorted.values

In [85]:
setRestaurantID = set(data["restaurant_id"])

In [86]:
restaurantID = np.sort(list(setRestaurantID))
restaurantID = restaurantID[::-1]

In [87]:
#i = 0
#j = 1
#print(data_sorted_array[i,7], restaurantID[j])

In [88]:
size = len(data_sorted_array)
j=0
for i in range(size):
    while(data_sorted_array[i,7] != restaurantID[j]):
        #print(i, j)
        j+=1
    data_sorted_array[i, 7] = j

In [89]:
#itemDayHour
data_sorted_array = data_sorted_array[:,1:]


array([[5867166128242373928, 17525, 6, ..., '769e8210-976', 0, 1],
       [430533841450840734, 48244, 5, ..., 'bda1ca0b-070', 0, 1],
       [5867166128242373928, 48752, 6, ..., '435a9e83-24e', 0, 1],
       ..., 
       [6382516717860657683, 50869, 4, ..., '7b10c77f-aac', 3356, 1],
       [-2985130882865154889, 50334, 6, ..., '7b10c77f-aac', 3356, 1],
       [-771899697155891775, 50869, 4, ..., '7b10c77f-aac', 3356, 1]], dtype=object)

In [90]:
#pandas.DataFrame(itemDayHour).to_csv("data_2_.csv")
pandas.DataFrame(data_sorted_array).to_csv("itemID_resID_sorted.csv")

In [91]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

In [148]:
X = data_sorted_array[:,[2,3,6]]

In [158]:
print(np.where((X[:,0] == 6) & (X[:,1] == 23) & (X[:,2] == 3356)))
X

(array([323136], dtype=int64),)


array([[6, 23, 0],
       [5, 22, 0],
       [6, 23, 0],
       ..., 
       [4, 0, 3356],
       [6, 23, 3356],
       [4, 22, 3356]], dtype=object)

In [151]:
Y = data_sorted_array[:,1].astype(np.int)

In [156]:
#print(Y[323120], Y[323126], Y[323133], Y[323135])
#print(Y)
print(data_sorted_array[323120], data_sorted_array[323126], data_sorted_array[323133], data_sorted_array[323135])

50334 16982 41770 50869
[17525 48244 48752 ..., 50869 50334 50869]
[6382516717860657683 50334 4 0 '81beda5f-34b' '7b10c77f-aac' 3356 1] [6382516717860657683 16982 4 0 '81beda5f-34b' '7b10c77f-aac' 3356 1] [6382516717860657683 41770 4 0 '81beda5f-34b' '7b10c77f-aac' 3356 1] [6382516717860657683 50869 4 0 '81beda5f-34b' '7b10c77f-aac' 3356 1]


In [154]:
clf.fit(X, Y)

GaussianNB(priors=None)

In [1]:
pred = [6, 23, -3356]
print(clf.predict([pred]))
print(clf.predict_proba([pred]))

NameError: name 'clf' is not defined

In [179]:
clf.classes_

array([    0,     1,     2, ..., 53400, 53401, 53402])

In [2]:
print(clf.predict_proba([pred])[0][50334]) 
# pred = [6,23,3356] means at day=6, hour=23, restaurant=3356, probability of ordeing the item 50334 is 0.633303045812

NameError: name 'clf' is not defined

In [ ]:
#P(day,hour,restaurant|item) = ( P() )
P(item|day,hour,restaurant) = ( P(day|item)*P(hour|item)*P(restaurant|item) ) * P(item) / P(day, hour, restaurant)
Here, P(restaurant|item) is 1, because, every item_id belongs to only one restaurant(i.e. only one restaurant_id). 
So given an item, the restaurant is always a certain one.
As a result we can easily omit P(restaurant|item) from our calculation and condition only on "day" and "hour".