In [104]:
fileName ="data_2_.csv"

In [105]:
import pandas
import numpy as np
import heapq

In [169]:
data= pandas.read_csv(fileName)

In [170]:
data_sorted = data.sort_values(['restaurant_id'], ascending=True)
data_sorted_array = data_sorted.values
setRestaurantID = set(data["restaurant_id"])
restaurantID = np.sort(list(setRestaurantID))
"""
i = 0
j = 0
print(data_sorted_array[i,7], restaurantID[j])
"""
size = len(data_sorted_array)
print(size)
j=0
for i in range(size):
    while(data_sorted_array[i,7] != restaurantID[j]):
        #print(i, j)
        j+=1
    data_sorted_array[i, 7] = j
    
data_sorted_array = data_sorted_array[:,1:]
data_sorted_array

323138


array([[-771899697155891775, 50869, 4, ..., '7b10c77f-aac', 0, 1],
       [1510112086545274614, 16982, 2, ..., '7b10c77f-aac', 0, 1],
       [-6872960916617605148, 824, 5, ..., 'b2474220-96c', 0, 1],
       ..., 
       [5867166128242373928, 17525, 6, ..., '769e8210-976', 3356, 1],
       [-3277971590148499419, 26101, 3, ..., 'c9aa3993-86f', 3356, 1],
       [430533841450840734, 395, 7, ..., 'bda1ca0b-070', 3356, 1]], dtype=object)

In [171]:
data_sorted_array = np.array(sorted(data_sorted_array, key=lambda a_entry: a_entry[0]) )
userID_set = set(data_sorted["user_id"])
userID_list = np.sort(list(userID_set))
size = len(data_sorted_array)
j=0
"""
i = -1
j = -1
print(data_sorted_array[i,0], userID_list[j])
"""
for i in range(size):
    while(data_sorted_array[i,0] != userID_list[j]):
        #print(i, j)
        j+=1
    data_sorted_array[i, 0] = j

In [172]:
data_sorted_array = np.array(sorted(data_sorted_array, key=lambda a_entry: str(a_entry[4])) )
print(data_sorted_array[-5:])
categoryID_set = set(data_sorted["category_id"])
categoryID_list = np.sort(list(categoryID_set))
#print(categoryID_list, categoryID_set)
size = len(data_sorted_array)
categoryID_list[-5:]

[[20254 10104 5 18 nan '7b10c77f-aac' 843 1]
 [20254 19434 5 18 nan '7b10c77f-aac' 843 1]
 [20254 28902 5 18 nan '6fcdf421-55d' 843 1]
 [20254 20490 5 18 nan '7b10c77f-aac' 843 1]
 [21840 15132 7 23 nan '7b10c77f-aac' 154 1]]


array(['fff2d0b0-9e4', 'fff55c7e-1ed', 'fff6b57c-752', 'fffda23f-efd',
       'nan'],
      dtype='<U32')

In [173]:
#"""
i = -1
j = -1
#data_sorted_array[:,4].replace(np.nan,"nan")
print(type(data_sorted_array[i,4]), type(categoryID_list[j]))
print((data_sorted_array[i,4]), (categoryID_list[j]))
#"""
j=0
for i in range(size):
    if type(data_sorted_array[i,4]) == float:
#        print(data_sorted_array[i,4])
        data_sorted_array[i,4] = "nan"
    while(data_sorted_array[i,4] != categoryID_list[j]):
#        print(i, j)
        j+=1
    data_sorted_array[i, 4] = j
#"""

<class 'float'> <class 'numpy.str_'>
nan nan


In [174]:
data_sorted_array = np.array(sorted(data_sorted_array, key=lambda a_entry: str(a_entry[5])) )
print(data_sorted_array[-5:])
cusineID_set = set(data_sorted["cusine_id"])
cusineID_list = np.sort(list(cusineID_set))
size = len(data_sorted_array)
cusineID_list[-5:]

#"""
i = -1
j = -1
print(type(data_sorted_array[i,5]), type(cusineID_list[j]))
print((data_sorted_array[i,5]), (cusineID_list[j]))
#"""

j=0
for i in range(size):
    if type(data_sorted_array[i,5]) == float:
        print(data_sorted_array[i,5])
        data_sorted_array[i,5] = "nan"
    while(data_sorted_array[i,5] != cusineID_list[j]):
        print(i, j)
        j+=1
    data_sorted_array[i, 5] = j
#"""

[[55480 34863 7 6 15117 'fe93edb5-39e' 965 1]
 [61374 34863 5 3 15117 'fe93edb5-39e' 965 1]
 [34260 774 4 20 6306 nan 1521 1]
 [5353 15645 1 3 10643 nan 216 1]
 [14523 15645 2 1 10643 nan 216 1]]
<class 'float'> <class 'numpy.str_'>
nan nan
16749 0
26748 1
27323 2
37141 3
47300 4
58967 5
60047 6
60569 7
72121 8
125426 9
126798 10
144013 11
146803 12
149600 13
151132 14
151135 15
151527 16
157547 17
162925 18
162941 19
174752 20
177052 21
177213 22
203599 23
205116 24
207173 25
209043 26
246620 27
247219 28
247323 29
252794 30
253331 31
277101 32
278816 33
293252 34
293767 35
295001 36
295014 37
299119 38
302458 39
309374 40
309450 41
318810 42
318896 43
319213 44
nan
323135 45
nan
nan


In [175]:
pandas.DataFrame(data_sorted_array).to_csv("data_in_numeric_form.csv")

In [62]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

In [63]:
pivot = int(len(data_sorted_array)*.8)

In [64]:
X_train = data_sorted_array[:pivot,[2,3]]
Y_train = data_sorted_array[:pivot,1].astype(np.int)
X_test = data_sorted_array[pivot:,[2,3]]
Y_test = data_sorted_array[pivot:,1].astype(np.int)

In [65]:
clf.fit(X_train, Y_train)

GaussianNB(priors=None)

In [66]:
#print(np.where((X[:,0] == -6) & (X[:,1] == -23) & (X[:,2] == -3356)))
X[28526]

array([3, 2], dtype=object)

In [67]:
#print(Y[323120], Y[323126], Y[323133], Y[323135])
print(Y)
#print(data_sorted_array[323120], data_sorted_array[323126], data_sorted_array[323133], data_sorted_array[323135])

[27495 15276 42632 ..., 50395  1748 36894]


In [97]:
pred = [3, 2]
print(clf.predict([pred]))

[28418]


In [98]:
probs = clf.predict_proba([pred])
idx = probs.argsort()[0][-10:][::-1]
print(probs[0][idx])
print(X_train[idx])
print(Y_train[idx])


[ 0.00561714  0.00561714  0.00561714  0.00280857  0.00280857  0.00280857
  0.00280857  0.00280857  0.00280857  0.00280857]
[[1 22]
 [2 21]
 [3 23]
 [3 0]
 [6 4]
 [5 16]
 [6 23]
 [6 17]
 [7 20]
 [5 3]]
[ 2028  2161   246 47379  3467 22055 11444 40780 20979 45814]


In [ ]:
clf.classes_

In [ ]:
print(clf.predict_proba([pred])[0][50334]) 
# pred = [6,23,3356] means at day=6, hour=23, restaurant=3356, probability of ordeing the item 50334 is 0.633303045812

P(item|day,hour,restaurant) = ( P(day|item)*P(hour|item)*P(restaurant|item) ) * P(item) / P(day, hour, restaurant)
Here, P(restaurant|item) is 1, because, every item_id belongs to only one restaurant(i.e. only one restaurant_id). 
So given an item, the restaurant is always a certain one.
As a result we can easily omit P(restaurant|item) from our calculation and condition only on "day" and "hour".